# description: From Git Push to Production – Seamlessly
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme
# - jekyll-feed
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-paginate

title: Dheeman Das
description: From Git Push to Production – Seamlessly
author: Dheeman Das

# Theme
remote_theme: pages-themes/cayman@v0.2.0

# Plugins (safe for GitHub Pages)
plugins:
  - jekyll-remote-theme
  - jekyll-feed           # RSS feed at /feed.xml
  - jekyll-sitemap        # SEO sitemap at /sitemap.xml
  - jekyll-seo-tag        # Meta tags for SEO and social sharing
  - jekyll-paginate       # Pagination for blog posts (if you use a blog)

# SEO plugin config (optional)
seo:
  type: personal
  github: Reliable-Royalty-29
  name: Dheeman Das
  description: DevOps Engineer | Portfolio

# Pagination settings (if used)
paginate: 5
paginate_path: "/page:num"

# Site settings
url: "https://dheeman29.github.io"   # Replace with your GitHub Pages URL
baseurl: ""                          # Leave empty if deploying to root
markdown: kramdown
theme: null

# Exclude these from the final build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Build settings
future: true
strict_front_matter: false

