title: Dheeman Das
logo: /assets/img/My_Image.png
description: CI/CD Pipeline Automation Specialist
# show_downloads: true
# theme:  jekyll-theme-minimal
# skin: dark
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
 
