title: Dheeman Das
logo: /assets/img/IMG-20240323-WA0002-01-photoaidcom-cropped.jpeg
description: CI/CD Pipeline Automation Specialist | Infrastructure as Code (IaC) Advocate | Docker & Kubernetes Enthusiast
# show_downloads: true
theme: jekyll-theme-minimal
