title: Dheeman Das
logo: /assets/img/headshot_circle.png
description: CI/CD Pipeline Automation Specialist | Infrastructure as Code (IaC) Advocate | Docker & Kubernetes Enthusiast
# show_downloads: true
theme: jekyll-theme-minimal
