title: Dheeman Das
logo: /assets/img/My_Image.png
description: Dheeman Das
description: From Git Push to Production – Seamlessly
# show_downloads: true
# theme:  jekyll-theme-minimal
# skin: dark
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
 
